services:
  - type: web
    name: siri-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_EMAILJS_SERVICE_ID
        sync: false
      - key: NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
        sync: false
      - key: NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
        sync: false
